/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OneSteven (https://sketchfab.com/Steven007)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/jaguar-c-x75-c394e047dd264df29438c5c41b1c2336
title: Jaguar C-X75
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../public/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[130.58, -37.23, 221.71]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 10]}
            scale={[1.6, 1.6, 1.6]}>
            <mesh geometry={nodes.wheel_Material005_0.geometry} material={nodes.wheel_Material005_0.material} />
            <mesh geometry={nodes.wheel_Material004_0.geometry} material={nodes.wheel_Material004_0.material} />
            <mesh geometry={nodes.wheel_rims002_0.geometry} material={nodes.wheel_rims002_0.material} />
          </group>
          <group position={[130.58, -37.23, 221.71]} rotation={[0.01, -0.31, 0]} scale={[1.44, 1.44, 1.44]}>
            <mesh geometry={nodes.cal_Material006_0.geometry} material={nodes.cal_Material006_0.material} />
          </group>
          <group position={[-0.89, 5.58, 11.46]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum025_cb_0.geometry} material={materials.material} />
          </group>
          <group position={[-0.89, 5.99, -14.25]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum024_flack_0.geometry} material={nodes.gum024_flack_0.material} />
          </group>
          <group position={[-0.89, 44.75, 101.43]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum023_refl_0.geometry} material={materials.refl} />
          </group>
          <group position={[-0.68, 38.77, -323.46]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum021_chr_0.geometry} material={materials.material_7} />
          </group>
          <group position={[-0.89, 25.42, -290.61]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum019_remit_0.geometry} material={materials.remit} />
          </group>
          <group position={[-0.89, 12.66, 278.07]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum018_glack_0.geometry} material={materials.glack} />
          </group>
          <group position={[-0.89, 11.54, 276.34]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum017_xen_0.geometry} material={materials.material_10} />
          </group>
          <group position={[-0.89, 10.72, 283.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum015_emit_0.geometry} material={materials.emit} />
          </group>
          <group position={[-0.89, 53.23, -9.68]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum014_flack_0.geometry} material={nodes.gum014_flack_0.material} />
          </group>
          <group position={[-0.89, 25.37, -289.71]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum012_Material003_0.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-0.89, 56.37, -15.75]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum010_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-0.89, 8.89, -11.7]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum009_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-0.89, 13.91, 14.9]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum003_griils_0.geometry} material={materials.griils} />
          </group>
          <group position={[-0.4, 13.06, 13.63]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum001_bod_0.geometry} material={materials.material_16} />
          </group>
          <group position={[-0.89, 2.91, 42.64]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum000_flack_0.geometry} material={nodes.gum000_flack_0.material} />
          </group>
          <group position={[-0.89, 41.27, 106.94]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.9, 3.9, 3.9]}>
            <mesh geometry={nodes.gum002_LED_0.geometry} material={materials.material_17} />
          </group>
          <group position={[-130.58, -37.23, 221.71]} rotation={[-Math.PI / 2, 0, 2.83]} scale={[1.6, 1.6, 1.6]}>
            <mesh geometry={nodes.wheel001_Material005_0.geometry} material={nodes.wheel001_Material005_0.material} />
            <mesh geometry={nodes.wheel001_Material004_0.geometry} material={nodes.wheel001_Material004_0.material} />
            <mesh geometry={nodes.wheel001_rims002_0.geometry} material={nodes.wheel001_rims002_0.material} />
          </group>
          <group position={[-130.58, -37.23, 221.71]} rotation={[0.01, -0.31, 0]} scale={[-1.44, 1.44, 1.44]}>
            <mesh geometry={nodes.cal001_Material006_0.geometry} material={nodes.cal001_Material006_0.material} />
          </group>
          <group position={[-134.72, -34.17, -196.39]} rotation={[3.14, 0, 0]} scale={[-1.48, 1.54, 1.54]}>
            <mesh geometry={nodes.cal002_Material006_0.geometry} material={nodes.cal002_Material006_0.material} />
          </group>
          <group position={[-134.72, -34.17, -196.39]} rotation={[1.56, 0, -Math.PI]} scale={[1.65, 1.72, 1.72]}>
            <mesh geometry={nodes.wheel002_Material005_0.geometry} material={nodes.wheel002_Material005_0.material} />
            <mesh geometry={nodes.wheel002_Material004_0.geometry} material={nodes.wheel002_Material004_0.material} />
            <mesh geometry={nodes.wheel002_rims002_0.geometry} material={nodes.wheel002_rims002_0.material} />
          </group>
          <group position={[134.72, -34.17, -196.39]} rotation={[3.14, 0, 0]} scale={[1.48, 1.54, 1.54]}>
            <mesh geometry={nodes.cal003_Material006_0.geometry} material={nodes.cal003_Material006_0.material} />
          </group>
          <group position={[134.72, -34.17, -196.39]} rotation={[1.56, 0, 0]} scale={[1.65, 1.72, 1.72]}>
            <mesh geometry={nodes.wheel003_Material005_0.geometry} material={nodes.wheel003_Material005_0.material} />
            <mesh geometry={nodes.wheel003_Material004_0.geometry} material={nodes.wheel003_Material004_0.material} />
            <mesh geometry={nodes.wheel003_rims002_0.geometry} material={nodes.wheel003_rims002_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../public/scene.gltf')
